### PR TITLE
Separate configuration and data directories

### PR DESCRIPTION
**Pull request by kwentine**
The first step towards a "containerized" data build step is to separate configuration files from the generated data.
This pull requests cleaves the former contents of the `data` directory in twain:
- `config` contains the species-specific `config.yml` files that we edit
- `data` contains everything else that is generated by `make`

In Kubernetes context, the latter `data` directory (which can be changed through `make DATA_DIR=some_other_location`) is where our persistent volume will be mounted.

To test the changes, once you have checked-out this branch:
```bash
# Cleanup 
rm targets.mk
# Optionally remove some data files
#  ...
# Then:
make build
```  
If you encounter any issues, have remarks or questions, you may report them below. Otherwise you can approve the PR.

The next step, after this PR is merged, is for me to populate the `data.dockerfile` placeholder prepared by Rory.

### CODE REVIEW

**Comment by RMCrean** [comment]
Hey! 

Thanks for this. After checking out your branch I ran the below command but got the following error message: 

```
❯ rm targets.mk ; make build
Downloading data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz ...
/bin/bash: command substitution: line 3: syntax error near unexpected token `)'
/bin/bash: command substitution: line 3: `< )"'
make: *** [Makefile:139: data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz] Error 1
```

**Comment by brinkdp** [comment]
Hi! I get a very similar error (running with my MacOS fix):
```
❯ rm targets.mk
❯ make build SHELL=/opt/homebrew/bin/bash
Makefile:11: targets.mk: No such file or directory
/opt/homebrew/bin/bash: -c: line 1: syntax error near unexpected token `)'
/opt/homebrew/bin/bash: -c: line 1: `echo "Downloading data/parnassius_mnemosyne/CAVLGL01.fna.gz ..."; curl -# -L --output data/parnassius_mnemosyne/CAVLGL01.fna.gz "$(< )"'
make: *** [data/parnassius_mnemosyne/CAVLGL01.fna.gz] Error 127
```

**Comment by kwentine** [comment]
Thank you both! It was obviously a matter of `$$( < $|)` rather than `$$(< $<)` 🙄 I hope you won't encounter more errors. In any case the Dockerfile is on its way, so bear with me 🙏🏻

**Comment by RMCrean** [comment]
Thanks, I just tried the changes now, with all the data files already downloaded (from a prior run) and stored inside data folder it worked nicely (and I saw the squirrel ;) ). 

But then I tried deleting one of the data directories (aspergillus_nidulans) and running it again:
```
rm targets.mk ; make build
Downloading data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz ...
Warning: Failed to create the file                                                                                   
Warning: data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz: 
Warning: No such file or directory
                                                                                                                  0,2%curl: (23) Failure writing output to destination

make: *** [Makefile:139: data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz] Error 23`
```

I then recreated the folder myself at the path: `data/aspergillus_nidulans` and reran the command. Now it works successfully: 

```
rm targets.mk ; make build
Downloading data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz ...
############################################################################################################### 100,0%
Downloading data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.gff.gz ...
############################################################################################################### 100,0%
Downloaded data files
  - data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.gz
  - data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.gff.gz
  - data/linum_trigynum/CAXIPQ01.fna.gz
  - data/linum_tenue/CAMGYJ01.fna.gz
  - data/parnassius_mnemosyne/CAVLGL01.fna.gz
  - data/parnassius_mnemosyne/GCA_963668995.1_Parnassius_mnemosyne_n_2023_11_genomic.gff.gz
  - data/clupea_harengus/GCF_900700415.2_Ch_v2.0.2_genomic.gff.gz
Creating index for data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.gff.bgz
Indexed GFF files
  - data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.gff.bgz.tbi
  - data/parnassius_mnemosyne/GCA_963668995.1_Parnassius_mnemosyne_n_2023_11_genomic.gff.bgz.tbi
  - data/clupea_harengus/GCF_900700415.2_Ch_v2.0.2_genomic.gff.bgz.tbi
Indexing FASTA file data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.bgz
Indexed FASTA files
  - data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.bgz.{fai,gzi}
  - data/linum_trigynum/CAXIPQ01.fna.bgz.{fai,gzi}
  - data/linum_tenue/CAMGYJ01.fna.bgz.{fai,gzi}
  - data/parnassius_mnemosyne/CAVLGL01.fna.bgz.{fai,gzi}
/bin/bash scripts/generate_jbrowse_config.sh data/aspergillus_nidulans/config.json config/aspergillus_nidulans/config.yml
Using existing local file data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.fna.bgz
Added assembly "ASM1142v1" to data/aspergillus_nidulans/config.json
Using existing local file data/aspergillus_nidulans/GCF_000011425.1_ASM1142v1_genomic.gff.bgz
Added track with name "Protein coding genes" and trackId "GCF_000011425.1_ASM1142v1_genomic.gff" to data/aspergillus_nidulans/config.json
Added connection "UCSC asembly hub" to data/aspergillus_nidulans/config.json
Generated JBrowse configuration in directories
  📁 data/aspergillus_nidulans
  📁 data/linum_trigynum
  📁 data/linum_tenue
  📁 data/parnassius_mnemosyne
  📁 data/clupea_harengus
```

So it seems like it just needs a make folder if not exists and then LGTM. I will approve the PR now but feel free to ask me to re-review/re-check if you want :)

**Review by RMCrean — APPROVED** [review]

**Comment by brinkdp** [comment]
Thanks! Same for me, ran `make build` and got the missing dir error again. After following Rory's comment to delete and recreate the species dirs in data/ it exceuted fine. 

(well, apart from an error related to the unsupported .gtf in the linum_trigynum config. But that one is on me, I thought I had commented out the lines calling to that file...)

So out of curiosity I tested to clone the branch to a new local dir to get a fresh start. Checking out the branch there and running make build resulted in the same error again. 
```
❯ rm targets.mk; make build SHELL=/opt/homebrew/bin/bash
Makefile:11: targets.mk: No such file or directory
Downloading data/parnassius_mnemosyne/CAVLGL01.fna.gz ...
Warning: Failed to open the file data/parnassius_mnemosyne/CAVLGL01.fna.gz: No                      
Warning: such file or directory
curl: (23) Failure writing output to destination

make: *** [data/parnassius_mnemosyne/CAVLGL01.fna.gz] Error 23
```
I now noticed that the makefile creates `data/`, `data/.downloads/`  but not the species folders in `data/`. This is likely the reason for the error we have been getting. Indeed, running 

`mkdir data/parnassius_mnemosyne; rm targets.mk; make build SHELL=/opt/homebrew/bin/bash`

makes the makefile download the first species (and then stops at the next species, as expected). I didn't look at the makefile itself, but I suspect that it might need a line that checks if the species subdirs exists in `data/` (and not just in `.downloads/`) and creates them if the are missing.

Other than this, it looks good to me. But I'll wait to hear your thoughts Quentin before approving the PR.

**Comment by kwentine** [comment]
Thanks again. The fix is in f3c3f40, using one of curl's famously innumerable options. I will merge this now and continue working on the dockerized build.

As a side note: I realize that this is time consuming for both of you, and that some testing mechanism lacks. So here is an idea:
```bash
mkdir -p tests/config
# We handcraft a few configuration files with `localhost` URLs
# We create the corresponding dummy or lightweight FASTA GFF etc... in the following:
mkdir -p tests/resources
# Then we can test the build using
python -m http.server tests/resources
make CONFIG_DIR=tests/config DATA_DIR=/tmp/data build
```

**Review by brinkdp — APPROVED** [review]

**Comment by brinkdp** [comment]
Good idea! Having a test that uses lightweight data (i.e. not the herring and butterfly :) ) would be useful and probably save us time in the long run.

**Pull request merged**
